### ISSUE TITLE
下载脚本的几个问题

### ISSUE THREAD

**Issue by mocuishlelin** [OllieGo/Raccon#1]
1. img 保存均保存于 images 下且每篇文章的图片均从 1 开始命名，所以均会重复覆盖图片。
2. 文章标题名带有某些字符会报错，如："/"  , "|" 。

稍作更改：https://github.com/mocuishlelin/Raccon/blob/master/DownloadArticles.py
感谢分享源码。

**Comment by OllieGo** [comment]
感谢指正，已优化
